#!/usr/bin/env python
# User: janmejay.singh
# Time: 31 Oct, 2009 02:07:18 AM

import pygame

from src import init
from player_loader import PlayerLoader
from util import actions

pygame.init()

screen = pygame.display.set_mode((1024, 768))

player_loader = PlayerLoader()
player_loader.load(screen)
while True:
    player_loader.draw()
    pygame.display.flip()

