#!/usr/bin/env ruby
# User: janmejay.singh
# Time: 16 Jun, 2008 8:20:18 PM

require File.join(File.dirname(__FILE__), 'src', 'init')

require 'bakery_wizard'
require 'player_loader'
require 'game_loader'
require 'shop'
require 'serialization_defaulter'

$wizard = BakeryWizard.new
$wizard.add(PlayerLoader)
$wizard.add(GameLoader)
$wizard.add(Shop)
$wizard.show