# User: janmejay.singh
# Time: 19 Jun, 2008 12:07:35 AM
module ZOrder
   BACKGROUND, UNDER_TABLE_EQUIPMENTS, CAKE_IN_DUSTBIN, TABLE, OVEN_TRASH_CAN, OVEN_CAKE_HOLDER, PLATE, CAKE, OVEN, OVEN_CONTROLS, 
   PROCESSING, CURSOR, BAKER, PLATE_WHEN_IN_BAKERS_HAND, CAKE_WHEN_IN_BAKERS_HAND, BAKER_HAT, MESSAGES = *0..16
end
