# User: janmejay.singh
# Time: 19 Jun, 2008 12:07:35 AM
module ZOrder
   BACKGROUND, UNDER_TABLE_EQUIPMENTS, TABLE, OVEN_CAKE_HOLDER, PLATE, CAKE, OVEN, OVEN_CONTROLS, PROCESSING, CURSOR, BAKER, MESSAGES = *0..11
end
