# User: janmejay.singh
# Time: 19 Jun, 2008 12:07:35 AM
module ZOrder
   BACKGROUND, UNDER_TABLE_EQUIPMENTS, CAKE_IN_DUSTBIN, TABLE, TV, TABLE_MOUNTED_EQUIPMENTS, TABLE_MOUNTED_CONTROLS, CUSTOMER, ORDER_BUBBLE, OVEN_TRASH_CAN, 
   OVEN_CAKE_HOLDER, PLATE, CAKE, OVEN, OVEN_CONTROLS, ACTION_CLOWD, SHOWCASE_COVER, PROCESSING, BAKER, PLATE_WHEN_IN_BAKERS_HAND, 
   CAKE_WHEN_IN_BAKERS_HAND, BAKER_HAT, MESSAGES, MODAL_PANES, MODAL_BUTTONS, CURSOR = *0..25
end
